version: '3.8'
services:

  db:
    image: postgres:17-alpine
    container_name: search-engine-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search_engine_db