version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: search-engine-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search_engine_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d search_engine_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: search-engine-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./sites.yml:/app/config/external-sites.yml
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - HIKARI_TIMEOUT=20000
      - HIBERNATE_DDL_AUTO=update
      - SHOW_SQL=false
      - SPRING_CONFIG_IMPORT=file:/app/config/external-sites.yml
volumes:
  postgres_data: