server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/search_engine_db?currentSchema=search_engine_schema
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS search_engine_schema
      connection-timeout: ${HIKARI_TIMEOUT:20000}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

indexing-settings:
  sites:
    - url: https://dimonvideo.ru/
      name: Dimon Video

jsoup-settings:
  agent: ${JSOUP_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36}
  referrer: http://www.google.com